Add apis-list/apis-list
bayandin/awesome-awesomeness pull request #431
Opened 2021-01-25 08:29 UTC by trntv

Add https://github.com/apis-list/apis-list

**https://github.com/apis-list/apis-list**

**Community maintained, human and machine readable list of Public APIs**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- [x] I have read and understood the [contribution guidelines](https://github.com/bayandin/awesome-awesomeness/blob/master/CONTRIBUTING.md).
- [x] This pull request has a descriptive title. For example, `Add [Name of List]`, not `Update readme.md` or `Add an awesome list`.
- [x] The list I added **has been around for at least 20 days**,
- [x] The list I added is a non-generated Markdown file in a GitHub repo,
- [x] The list I added is not a duplicate

2022-08-16 22:40 UTC, Acumane requested changes

2022-08-16 22:40 UTC, Acumane commented on README.md
> +	        - [by @apis-list](https://github.com/apis-list/apis-list)
Fix indentation:
```suggestion
	    - [by @apis-list](https://github.com/apis-list/apis-list)
```

2022-08-16 22:42 UTC, SpinYang commented
这是来自QQ邮箱的自动回复邮件。
 
您的邮件已收到，谢谢。
 
YY

2024-01-11 20:20 UTC, closed without merging

2024-01-11 20:23 UTC, SpinYang commented
这是来自QQ邮箱的自动回复邮件。
 
您的邮件已收到，谢谢。
 
YY